site_name: Шаблоны документов учреждения (ФБУ "Ивановский ЦСМ")

repo_url: https://github.com/csm-ivanovo-ru/DocTemplates

# nav:
# - В начало: 'index.md'

docs_dir: docs

theme: readthedocs
