name: Build and test
on: [push]
jobs:
  build-and-test:
    name: Build and test
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"
          check-latest: true

      - name: Install choco packages
        run: |
          choco install gitversion.portable -y

      - name: Install required PowerShell and NuGet modules
        shell: powershell
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted;
          Install-Module -Name InvokeBuild -Verbose | Out-Null;
          Install-Module -Name 7Zip4Powershell -Verbose | Out-Null;
          Register-PackageSource -Name 'nuget.org' -Location 'https://api.nuget.org/v3/index.json' -ProviderName NuGet -Trusted -Force -Verbose | Out-Null;
          Install-Package -Name 'Saxon-HE' -MinimumVersion '9.8' -MaximumVersion '9.8.999' -ProviderName NuGet -Verbose | Out-Null;
          Install-Package -Name 'QRCoder' -ProviderName NuGet -SkipDependencies -Verbose | Out-Null;

      - name: Build .ott and .odt files
        shell: powershell
        run: |
          Import-Module -Name InvokeBuild | Out-Null;
          Invoke-Build -Task Build -Verbose;
