name: Check repository
on: [push]
jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout repository
        uses: Amadevus/pwsh-script@v2
        id: script
        with:
          script: |
            Install-Module -Name InvokeBuild -Verbose;
            Install-Module -Name 7Zip4Powershell -Verbose;

            Invoke-Build -Task Build -Verbose;
