name: Release to GihHub

on:
  push:
    # branches:
    #   - master

    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  actions: read
  contents: read
  deployments: write
  packages: write
  issues: write

jobs:
  release:
    name: Release to GihHub
    # needs: []
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"
          check-latest: true

      - name: Install required PowerShell and NuGet modules
        shell: powershell
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted;
          Install-Module -Name InvokeBuild | Out-Null;
          Install-Module -Name 7Zip4Powershell | Out-Null;
          Register-PackageSource -Name 'nuget.org' -Location 'https://api.nuget.org/v3/index.json' -ProviderName NuGet -Trusted -Force | Out-Null;
          Install-Package -Name 'Saxon-HE' -MinimumVersion '9.8' -MaximumVersion '9.8.999' -ProviderName NuGet | Out-Null;
          Install-Package -Name 'QRCoder' -ProviderName NuGet -SkipDependencies | Out-Null;

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with:
          useConfigFile: true

      - name: Build .ott and .odt files
        shell: powershell
        run: |
          Import-Module -Name InvokeBuild | Out-Null;
          Invoke-Build -Task Build -Version '${{ steps.gitversion.outputs.semVer }}';

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: |
            output/template/*.ott
            output/doc/*.odt
          # fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
