name: Release to GihHub

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  actions: read
  contents: write
  deployments: write
  issues: write

jobs:
  release:
    name: Release to GihHub
    runs-on: windows-latest
    env:
      version: "${{ github.ref_name }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Install dependencies
        id: install-dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build .ott and .odt files
        uses: IT-Service/Invoke-Build@v1.0.0
        with:
          task: "BuildAssets"
          verbose: true

      - name: Generate release notes
        id: generate-release-notes
        uses: IT-Service/New-ReleaseNotesFromChangeLog@v1.2.1
        with:
          version: "${{ env.version }}"
          verbose: true

      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "${{ steps.generate-release-notes.outputs.release-notes-path }}"
          files: "tmp/templatesAndDocs.zip"

      - name: Close the milestone
        uses: Akkjon/close-milestone@v2
        with:
          milestone_name: "${{ env.version }}"
          # description: |
          #   [![${{ env.version }}](https://img.shields.io/badge/release-${{ env.version }}-blue?style=plastic&logo=github)](${{ steps.create-release.outputs.url }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
