# https://github.com/microsoft/psscriptanalyzer-action
# https://github.com/PowerShell/PSScriptAnalyzer

name: Check PowerShell code quality

on:
  push:
    paths:
      - .github/workflows/powershell.yml
      - .build.ps1
      - src/**/*.ps1
      - tests/**/*.ps1
      - tests/**/*.psd1
      - tools/**/*.ps1
      - tools/**/*.psm1
      - tools/**/*.psd1

  pull_request:
    paths:
      - .github/workflows/powershell.yml
      - .build.ps1
      - src/**/*.ps1
      - tests/**/*.ps1
      - tests/**/*.psd1
      - tools/**/*.ps1
      - tools/**/*.psm1
      - tools/**/*.psd1

jobs:
  analyze:
    name: PSScriptAnalyzer
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Check tools, build and tests PowerShell scripts quality
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          # Check https://github.com/microsoft/psscriptanalyzer-action for more info about the options.
          includeDefaultRules: true
          excludeRule: '"PSUseDeclaredVarsMoreThanAssignments", "PSReviewUnusedParameter"'
          severity: '"Error", "Warning"'
          path: .\
          ignorePattern: "install"
          recurse: true
          output: results.sarif

      - name: Upload tools, build and tests PowerShell scripts checking results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
