name: Tests

on:
  push:
    paths:
      - .github/workflows/tests.yml
      - src/**
      - tools/**
      - tests/**
      - .build.ps1

  pull_request:
    paths:
      - .github/workflows/tests.yml
      - src/**
      - tools/**
      - tests/**
      - .build.ps1

jobs:
  build:
    name: Tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3.0.0
        id: java-setup
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "maven"

      - name: Restore NuGet packages for XSLT processing
        uses: IT-Service/restore-nuget-packages@v1.0.0
        with:
          packages-config-path: tools/xslt/packages.config
          packages-directory-path: tools/xslt/packages

      - name: Restore NuGet packages for QRCodes processing
        uses: IT-Service/restore-nuget-packages@v1.0.0
        with:
          packages-config-path: tools/QRCode/packages.config
          packages-directory-path: tools/QRCode/packages

      - name: Restore NuGet packages for images processing
        uses: IT-Service/restore-nuget-packages@v1.0.0
        with:
          packages-config-path: tools/Images/packages.config
          packages-directory-path: tools/Images/packages

      - name: Restore NuGet packages for GitVersion
        uses: IT-Service/restore-nuget-packages@v1.0.0
        with:
          packages-config-path: tools/GitVersion/packages.config
          packages-directory-path: tools/GitVersion/packages

      - name: Restore PowerShell modules
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          modules-to-cache: InvokeBuild:5.5.1, PowerShellForGitHub:0.16.0, 7Zip4Powershell:2.0.0, Pester:5.3.0
          shell: powershell

      - name: Build .ott and .odt files
        uses: IT-Service/Invoke-Build@v1.0.0
        with:
          task: "Build"
          verbose: true

      - name: Install ODFToolkit
        # if: steps.java-setup.outputs.cache-hit != 'true'
        # https://github.com/actions/setup-java/issues/306
        run: cd tests && mvn dependency:copy-dependencies

      - name: Validate documents and templates
        uses: zyborg/pester-tests-report@v1.5.0
        with:
          include_paths: tests
          report_title: Результаты тестирования
          tests_fail_step: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .ott files
        uses: actions/upload-artifact@v3.0.0
        with:
          name: doc-templates
          path: ${{ github.workspace }}/output/template/*.ott
          if-no-files-found: warn

      - name: Upload documents
        uses: actions/upload-artifact@v3.0.0
        with:
          name: docs
          path: |
            ${{ github.workspace }}/output/doc/
            !${{ github.workspace }}/output/doc/*/.dirstate
          if-no-files-found: warn
