name: Tests

on:
  push:
    paths:
      - .github/workflows/tests.yml
      - .github/actions/**
      - src/**
      - tools/**
      - tests/**
      - .build.ps1

  pull_request:
    paths:
      - .github/workflows/tests.yml
      - .github/actions/**
      - src/**
      - tools/**
      - tests/**
      - .build.ps1

jobs:
  build:
    name: Tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Install dependencies
        id: install-dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build .ott and .odt files
        uses: IT-Service/Invoke-Build@v1.0.0

      - name: Install ODFToolkit
        if: steps.install-dependencies.outputs.maven-cache-hit != 'true'
        run: cd tests && mvn dependency:copy-dependencies

      - name: Validate documents and templates
        uses: zyborg/pester-tests-report@v1.5.0
        with:
          include_paths: tests
          report_title: Результаты тестирования
          tests_fail_step: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .ott files
        uses: actions/upload-artifact@v3.0.0
        with:
          name: doc-templates
          path: ${{ github.workspace }}/output/template/*.ott
          if-no-files-found: warn

      - name: Upload documents
        uses: actions/upload-artifact@v3.0.0
        with:
          name: docs
          path: |
            ${{ github.workspace }}/output/doc/
            !${{ github.workspace }}/output/doc/*/.dirstate
          if-no-files-found: warn
