name: Tests

on:
  push:
    paths:
      - .github/workflows/tests.yml
      - src/**
      - tools/**
      - tests/**
      - .build.ps1

  pull_request:
    paths:
      - .github/workflows/tests.yml
      - src/**
      - tools/**
      - tests/**
      - .build.ps1

jobs:
  build:
    name: Tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
          check-latest: true

      - name: Install dependencies
        uses: IT-Service/Invoke-PSDepend@v1.0.0
        with:
          recurse: true

      - name: Build .ott and .odt files
        uses: IT-Service/Invoke-Build@v1.0.0
        with:
          task: "Build"
          verbose: true

      - name: Validate documents and templates
        uses: zyborg/pester-tests-report@v1
        with:
          include_paths: tests
          report_title: Результаты тестирования
          tests_fail_step: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .ott files
        uses: actions/upload-artifact@v2
        with:
          name: doc-templates
          path: ${{ github.workspace }}/output/template/*.ott
          if-no-files-found: warn

      - name: Upload documents
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            ${{ github.workspace }}/output/doc/
            !${{ github.workspace }}/output/doc/*/.dirstate
          if-no-files-found: warn
